name: basic-wi-parent

trigger: none

resources:
  webhooks:  ### Service Connections in Azure DevOps will not work with hyphens in the name.
    - webhook: Basic_WI_Parent          ### Webhook alias
      connection: Basic_WI_Parent    ### Incoming webhook service connection

steps:
- task: PowerShell@2
  inputs:
    filePath: 'ADO-Pipelines/scripts/Basic-WI-Parent.ps1'
    arguments: '-workitem ${{parameters.Basic_WI_Parent.resource.workItemId}}'